// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRzsxHhePh3MkoHFhMyv3xpB6o558E5aU',
    appId: '1:50718249193:web:928598a40aa0598c922078',
    messagingSenderId: '50718249193',
    projectId: 'chat-app-44794',
    authDomain: 'chat-app-44794.firebaseapp.com',
    storageBucket: 'chat-app-44794.firebasestorage.app',
    measurementId: 'G-M22CE9D533',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd1S7WkRkl_MualsWEVKt7v9CufrsBFik',
    appId: '1:50718249193:android:4e64fedca00e9f64922078',
    messagingSenderId: '50718249193',
    projectId: 'chat-app-44794',
    storageBucket: 'chat-app-44794.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjSRy7xyYx5eh-Y2qv6ThW-2OJ0MepcMQ',
    appId: '1:50718249193:ios:f7e9ff5c90001795922078',
    messagingSenderId: '50718249193',
    projectId: 'chat-app-44794',
    storageBucket: 'chat-app-44794.firebasestorage.app',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjSRy7xyYx5eh-Y2qv6ThW-2OJ0MepcMQ',
    appId: '1:50718249193:ios:f7e9ff5c90001795922078',
    messagingSenderId: '50718249193',
    projectId: 'chat-app-44794',
    storageBucket: 'chat-app-44794.firebasestorage.app',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRzsxHhePh3MkoHFhMyv3xpB6o558E5aU',
    appId: '1:50718249193:web:c7210afb8e0bf10b922078',
    messagingSenderId: '50718249193',
    projectId: 'chat-app-44794',
    authDomain: 'chat-app-44794.firebaseapp.com',
    storageBucket: 'chat-app-44794.firebasestorage.app',
    measurementId: 'G-473NMLGWQ8',
  );
}
